### ISSUE TITLE
关于猫咪识别的问题

### ISSUE THREAD

**Issue by yqdsaphd** [glerium/fanhai-cat-feeding#1]
up主你们好，我想请教一下关于喂猫机的猫咪识别依靠的是自己搭建的神经网络还是easydl的api？

**Comment by glerium** [comment]
我们视频里面用的是EasyDL的API，就是训练完模型之后导出SDK跑在服务器上。具体可以参考这个文档来部署：[https://ai.baidu.com/ai-doc/EASYDL/pk3qy9ave](https://ai.baidu.com/ai-doc/EASYDL/pk3qy9ave)

**Comment by yqdsaphd** [comment]
非常感谢^_^

**Comment by yqdsaphd** [comment]
非常感谢^_^
